name: Deploy Flatpak to self-hosted repository
on:
  push:
    tags:
      - "v*"
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@repo.tkmm.org << 'EOF'
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y jq xmlstarlet flatpak flatpak-builder          
          rm -rf ~/flathub
          git clone git@github.com:TKMM-Team/flathub.git --branch tkmm-pr
          cd ~/flathub
          bash update_metadata.sh
          flatpak-builder --user --repo=/var/www/html/repo --install-deps-from=flathub build io.github.tkmm_team.tkmm.yml
          flatpak build-export /var/www/html/repo build
          flatpak build-update-repo --generate-static-deltas /var/www/html/repo
          EOF
        env:
          USERNAME: ${{ secrets.USERNAME }}
